/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AppLayout: typeof import('./src/components/Layouts/AppLayout.vue')['default']
    AutoPlaySwiper: typeof import('./src/components/AutoPlaySwiper.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    BestSellerSection: typeof import('./src/components/HomePage/BestSellerSection.vue')['default']
    BlogCard: typeof import('./src/components/BlogCard.vue')['default']
    BlogSection: typeof import('./src/components/HomePage/BlogSection.vue')['default']
    CategoryAutoPlay: typeof import('./src/components/CategoryAutoPlay.vue')['default']
    CategoryCard: typeof import('./src/components/CategoryCard.vue')['default']
    CategorySection: typeof import('./src/components/HomePage/CategorySection.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Footer: typeof import('./src/components/Layouts/Footer.vue')['default']
    Gallary: typeof import('./src/components/Gallary.vue')['default']
    Header: typeof import('./src/components/Layouts/Header.vue')['default']
    Headline: typeof import('./src/components/Layouts/Headline.vue')['default']
    HeroSection: typeof import('./src/components/HomePage/HeroSection.vue')['default']
    HomepagePopup: typeof import('./src/components/HomePage/HomepagePopup.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    MobileNav: typeof import('./src/components/Layouts/MobileNav.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    MoreStationarySection: typeof import('./src/components/HomePage/MoreStationarySection.vue')['default']
    NavBar: typeof import('./src/components/Layouts/NavBar.vue')['default']
    NewArrivalsSection: typeof import('./src/components/HomePage/NewArrivalsSection.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PhoneGallary: typeof import('./src/components/PhoneGallary.vue')['default']
    PolicySection: typeof import('./src/components/HomePage/PolicySection.vue')['default']
    Preloader: typeof import('./src/components/Preloader.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductSection: typeof import('./src/components/HomePage/ProductSection.vue')['default']
    QualitySection: typeof import('./src/components/HomePage/QualitySection.vue')['default']
    ReturnpolicySection: typeof import('./src/components/HomePage/ReturnpolicySection.vue')['default']
    ReviweSection: typeof import('./src/components/HomePage/ReviweSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchHeader: typeof import('./src/components/Layouts/SearchHeader.vue')['default']
    ShopCard: typeof import('./src/components/ShopCard.vue')['default']
    SubMenuBar: typeof import('./src/components/Layouts/SubMenuBar.vue')['default']
    TopHeader: typeof import('./src/components/Layouts/TopHeader.vue')['default']
    VisitShopSection: typeof import('./src/components/HomePage/VisitShopSection.vue')['default']
    WishCard: typeof import('./src/components/WishCard.vue')['default']
    WishSideBar: typeof import('./src/components/WishSideBar.vue')['default']
    WorkingStep: typeof import('./src/components/WorkingStep.vue')['default']
  }
}
